version: '3'

services:
  alpine-sqs:
    image: roribio16/alpine-sqs:latest
    container_name: alpine-sqs
    volumes:
      - ./sqs:/opt/custom/
    ports:
      - "9324:9324"
      - "9325:9325"
    stdin_open: true
    tty: true
  celery-worker:
    build: .
    command: "cp celery/settings.cfg.example celery/settings.cfg && pip install -r requirements.txt && celery -A tasks worker -l info"
    restart: on-failure
    depends_on:
      - alpine-sqs